void ZappMass(int *mass, int *row);
void print_Two_Mass(int *mass, int *row, int *col);
void modulMax(int *mass, int *mass2, int col, int row);
void print_One_Mass(int *mass, int*row);
void modul2Max(int *mass, int *mass3, int col, int row);
void chetElement_Col(int*mass, int *mass2, int col, int row);
void nechet_Elemet_str(int*mass, int *mass2, int col, int row);
void search_Element(int*mass, int *mass2, int col, int str);
void summ_Elemnt(int*mass, int *mass2, int col, int str);
void krat3(int *mass, int *mass2, int col, int str);
void summ(int *mass, int row);
void Search_Min(int *mass, int row);
void Srednee(int *mass, int*row);
void pol_Number(int *mass, int*row);
void otr_Element(int *mass, int *row);